Upgrade Storybook to v6 [NP-714]
citizensadvice/design-system pull request #224
Opened 2020-09-11 11:48 UTC by davidrapson

Upgrade Storybook to v6

From the docs:

> presets.js has been renamed to main.js. main.js is the main point of configuration for storybook.
> config.js has been renamed to preview.js. preview.js configures the "preview" iframe that renders your components.
> addons.js has been renamed to manager.js. manager.js configures Storybook's "manager" UI that wraps the preview, and also configures addons panel.

In addition to structural changes the following config changes were needed:

- v6 support zero-config Typescript so `storybook/preset-typescript` is no longer required
- `withA11y` is no longer required, this code is injected by default with the add-on

2020-09-11 11:49 UTC, davidrapson commented on package.json
> +        "start": "npm run styleguide",
Added this by convention as I expected to be able to run `npm start`, aliases the existing styleguide command.

2020-09-11 12:01 UTC, davidsauntson approved these changes
Looks good to me.  

Only thing I noticed when running locally is that when you click on the 'Open this in new tab link', it opens something else.  Fine after I cleared my cache, just a heads up.

2020-09-11 13:10 UTC, davidrapson commented
> Only thing I noticed when running locally is that when you click on the 'Open this in new tab link', it opens something else (ie a different component). Fine after I cleared my cache, just a heads up.

Cheers, will see if I can replicate that.

This upgrade has already solved one bugbear for me. Prior to v6 storybook seemed to open in Chrome whenever you ran it. I don't use Chrome. Thankfully the upgrade now respects your default browser when running it (@soniaturcotte might appreciate this)

2020-09-11 16:03 UTC, davidrapson commented
@davidsauntson Have reliably been able to replicate the open in new tab issue. I noticed this was our own custom code but storybook provides a great default toolbar with this and a lot more. I've switched to use that.

**Before**

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/123386/92947937-92762a00-f450-11ea-9975-ddf186d2e73c.png">

**After**

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/123386/92947978-9d30bf00-f450-11ea-9ef6-c7fa9e353c18.png">


The second button from the right opens in a new tab, and reliably works.

2020-09-11 16:14 UTC, davidsauntson submitted a review, later dismissed
🥮 nice

2020-09-14 11:08 UTC, panosvoudouris commented
> @davidsauntson Have reliably been able to replicate the open in new tab issue. I noticed this was our own custom code but storybook provides a great default toolbar with this and a lot more. I've switched to use that.
> 
> **Before**
> 
> <img alt="image" width="1491" src="https://user-images.githubusercontent.com/123386/92947937-92762a00-f450-11ea-9975-ddf186d2e73c.png">
> 
> **After**
> 
> <img alt="image" width="1493" src="https://user-images.githubusercontent.com/123386/92947978-9d30bf00-f450-11ea-9ef6-c7fa9e353c18.png">
> 
> The second button from the right opens in a new tab, and reliably works.

We removed that bar and switched to the text as it was taking up a bit of space for effectively just that button. Also, non devs were finding it a bit confusing and where not sure how to open a component in a new window vs the text under the header. Check with Sonia to confirm which of the two is acceptable.

2020-09-14 11:09 UTC, panosvoudouris requested changes
See my comment about the bar.

Also add an entry to the top of the changelog for this ticket.

The addon panel has disappeared? Has the a11y checker.

2020-09-14 14:50 UTC, panosvoudouris approved these changes

2020-09-14 14:51 UTC, merged