Untag button feature specs
citizensadvice/design-system pull request #239
Opened 2020-09-23 16:01 UTC by davidrapson

Now that v1.10.0 has been released I should be able to untag the button feature specs as `@future_release`

2020-09-25 08:34 UTC, davidsauntson requested changes
These look like more visual tests in the behavioural test suite.

Let's delete them and replace them with equivalent tests in the vrt suite.

2020-09-25 08:35 UTC, luke-hill approved these changes

2020-09-25 08:36 UTC, luke-hill commented
These tests are doing actions (Denoted by the When steps). Ideally we should be testing these inside the cucumber suite, as the puppeteer stuff isn't as reliable with actions. (Also we cover more test candidates with browser/os combos).

2020-09-25 08:46 UTC, davidrapson commented
Seconding @davidsauntson's suggestion here. The cucumber tests here only assert that the colours are different based on the CSSOM which is not the same as confirming they _actually_ look right with a visual regression test. Should definitely have some behavioural tests but not sure they are an ideal fit for this sort of use-case.

2020-09-25 08:49 UTC, davidsauntson commented
@luke-hill I hear what you're saying and agree about the multiple browser issue, but they are testing hover states, which is a visual test.  

If backstop isn't working we should look at replacing it or fixing it - @davidrapson has used Percy before, which would cover the multiple browser issue.

2020-09-28 15:16 UTC, luke-hill commented
So we've looked into these tests just now, and not only can you not do them in BackstopJS they actually give you false confidence (As they don't work well with multiple actions).

I suggest for now we keep these tests here as a good source of truth with behavioural tests, and either look down the line to migrate the visual tests into the BDD suite using the Algorithm/Gem I made or look towards something like Percy (But percy would just wrap capybara which is the same thing).

2020-09-29 14:38 UTC, davidsauntson commented
OK, let's remove the hover states then and since the button update the backgrounds don't change on click anyway, so they can all go. 👍

2020-10-02 11:04 UTC, luke-hill commented
Dealt with in #254

2020-10-02 11:04 UTC, closed without merging